import { Item } from "../global";

const fn = (floor: string, top: string, type: boolean) => ({ floor, top, type })


export const priateMap: Item[][] = [
    [
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', 'light', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', 'pirate', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', 'pirate2', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', 'pirate3', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),

    ],
    [
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false)
    ],
    [
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),

    ],
    [
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false)
    ],
    [
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),

    ],
    [
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false)
    ],
    [
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),

    ],
    [
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', 'pirate3', true),
        fn('floor4', '', true),
        fn('floor2', '', true),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false)
    ],
    [
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),

    ],
    [
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false)
    ],
    [
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),

    ],
    [
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false)
    ],
    [
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),

    ],
    [
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false)
    ],
    [
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', '', false),
        fn('floor4', '', false),

    ]

]