import { MapBlock } from "../global";

const fn = (floor: string, top: string, type: boolean, prop?: string) => ({ floor, top, type, prop: <any>prop })

export const priateMap: MapBlock[][] = [
    [
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', 'box1', false, 'item_61'),
        fn('floor4', 'box1', false, 'item_62'),
        fn('floor2', 'box1', false, 'item_63'),
        fn('floor4', 'b1', true),
        fn('floor2', 'box1', false, 'item_61'),
        fn('floor4', 'box1', false, 'item_62'),
        fn('floor2', 'box1', false, 'item_63'),
        fn('floor4', 'b1', true),
        fn('floor2', 'box1', false, 'item_61'),
        fn('floor4', 'box1', false, 'item_61'),
        fn('floor2', 'box1', false, 'item_61'),
        fn('floor4', '', false),
        fn('floor2', '', false),
    ],
    [
        fn('floor4', '', false),
        fn('floor2', 'stone', true),
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', true),
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', true),
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
        fn('floor2', 'stone', true),
        fn('floor4', '', false)
    ],
    [
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', false),
    ],
    [
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
    ],
    [
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
        fn('floor2', 'pirate3', true),
        fn('floor4', '', true),
        fn('floor2', '', true),
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', false),
    ],
    [
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
    ],
    [
        fn('floor2', 'box1', false),
        fn('floor4', 'stone', true),
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', false),
        fn('floor4', 'stone', true),
        fn('floor2', 'box1', false),

    ],
    [
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', true),
        fn('floor4', 'box1', true),
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
    ],
    [
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
        fn('floor2', 'pirate3', true),
        fn('floor4', '', true),
        fn('floor2', '', true),
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', false),

    ],
    [
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
    ],
    [
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', false),
    ],
    [
        fn('floor4', '', false),
        fn('floor2', 'stone', true),
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
        fn('floor2', 'stone', true),
        fn('floor4', '', false),
    ],
    [
        fn('floor2', '', false),
        fn('floor4', '', false),
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', false),
        fn('floor4', 'b1', true),
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', false),
        fn('floor4', 'b1', true),
        fn('floor2', 'box1', false),
        fn('floor4', 'box1', false),
        fn('floor2', 'box1', false),
        fn('floor4', '', false),
        fn('floor2', '', false),

    ]

]