
export const COMMON_TEXTURE_LIST = [
  "assets/bazzi.png",
  "assets/bg.jpg",
  "assets/btn_blue.png",
  "assets/btn_create_room.png",
  "assets/btn_next_page.png",
  "assets/btn_pre_page.png",
  "assets/btn_room_start.png",
  "assets/custom_bubble_100.png",
  "assets/custom_bubble_101.png",
  "assets/custom_bubble_102.png",
  "assets/custom_bubble_103.png",
  "assets/custom_bubble_104.png",
  "assets/custom_bubble_105.png",
  "assets/custom_bubble_106.png",
  "assets/custom_bubble_107.png",
  "assets/custom_bubble_108.png",
  "assets/custom_bubble_95.png",
  "assets/custom_bubble_96.png",
  "assets/custom_bubble_97.png",
  "assets/custom_bubble_98.png",
  "assets/custom_bubble_99.png",
  "assets/hall.png",
  "assets/item_58.png",
  "assets/item_59.png",
  "assets/item_60.png",
  "assets/item_61.png",
  "assets/item_62.png",
  "assets/item_63.png",
  "assets/item_64.png",
  "assets/item_65.png",
  "assets/item_66.png",
  "assets/item_67.png",
  "assets/item_68.png",
  "assets/item_69.png",
  "assets/item_70.png",
  "assets/item_71.png",
  "assets/item_72.png",
  "assets/item_73.png",
  "assets/item_74.png",
  "assets/item_75.png",
  "assets/item_76.png",
  "assets/item_77.png",
  "assets/item_78.png",
  "assets/item_79.png",
  "assets/loading.png",
  "assets/map_flopy_tile2.png",
  "assets/map_pirate_object1.png",
  "assets/map_pirate_object5.png",
  "assets/map_pirate_tile2.png",
  "assets/map_pirate_tile6.png",
  "assets/room_card_bg.png",
  "assets/room_card_default_img.png",
  "assets/room_card_status_in_game.png",
  "assets/room_card_status_waiting.png",
  "assets/unit_bombwater.png"
]

export enum COMMON_TEXTURE {
  'bazzi.png' = 'assets/bazzi.png',
'bg.jpg' = 'assets/bg.jpg',
'btn_blue.png' = 'assets/btn_blue.png',
'btn_create_room.png' = 'assets/btn_create_room.png',
'btn_next_page.png' = 'assets/btn_next_page.png',
'btn_pre_page.png' = 'assets/btn_pre_page.png',
'btn_room_start.png' = 'assets/btn_room_start.png',
'custom_bubble_100.png' = 'assets/custom_bubble_100.png',
'custom_bubble_101.png' = 'assets/custom_bubble_101.png',
'custom_bubble_102.png' = 'assets/custom_bubble_102.png',
'custom_bubble_103.png' = 'assets/custom_bubble_103.png',
'custom_bubble_104.png' = 'assets/custom_bubble_104.png',
'custom_bubble_105.png' = 'assets/custom_bubble_105.png',
'custom_bubble_106.png' = 'assets/custom_bubble_106.png',
'custom_bubble_107.png' = 'assets/custom_bubble_107.png',
'custom_bubble_108.png' = 'assets/custom_bubble_108.png',
'custom_bubble_95.png' = 'assets/custom_bubble_95.png',
'custom_bubble_96.png' = 'assets/custom_bubble_96.png',
'custom_bubble_97.png' = 'assets/custom_bubble_97.png',
'custom_bubble_98.png' = 'assets/custom_bubble_98.png',
'custom_bubble_99.png' = 'assets/custom_bubble_99.png',
'hall.png' = 'assets/hall.png',
'item_58.png' = 'assets/item_58.png',
'item_59.png' = 'assets/item_59.png',
'item_60.png' = 'assets/item_60.png',
'item_61.png' = 'assets/item_61.png',
'item_62.png' = 'assets/item_62.png',
'item_63.png' = 'assets/item_63.png',
'item_64.png' = 'assets/item_64.png',
'item_65.png' = 'assets/item_65.png',
'item_66.png' = 'assets/item_66.png',
'item_67.png' = 'assets/item_67.png',
'item_68.png' = 'assets/item_68.png',
'item_69.png' = 'assets/item_69.png',
'item_70.png' = 'assets/item_70.png',
'item_71.png' = 'assets/item_71.png',
'item_72.png' = 'assets/item_72.png',
'item_73.png' = 'assets/item_73.png',
'item_74.png' = 'assets/item_74.png',
'item_75.png' = 'assets/item_75.png',
'item_76.png' = 'assets/item_76.png',
'item_77.png' = 'assets/item_77.png',
'item_78.png' = 'assets/item_78.png',
'item_79.png' = 'assets/item_79.png',
'loading.png' = 'assets/loading.png',
'map_flopy_tile2.png' = 'assets/map_flopy_tile2.png',
'map_pirate_object1.png' = 'assets/map_pirate_object1.png',
'map_pirate_object5.png' = 'assets/map_pirate_object5.png',
'map_pirate_tile2.png' = 'assets/map_pirate_tile2.png',
'map_pirate_tile6.png' = 'assets/map_pirate_tile6.png',
'room_card_bg.png' = 'assets/room_card_bg.png',
'room_card_default_img.png' = 'assets/room_card_default_img.png',
'room_card_status_in_game.png' = 'assets/room_card_status_in_game.png',
'room_card_status_waiting.png' = 'assets/room_card_status_waiting.png',
'unit_bombwater.png' = 'assets/unit_bombwater.png'
}
    