
export const COMMON_TEXTURE_LIST = [
  "assets/bazzi.png",
  "assets/bg.jpg",
  "assets/btn_blue.png",
  "assets/btn_create_room.png",
  "assets/btn_next_page.png",
  "assets/btn_pre_page.png",
  "assets/btn_room_start.png",
  "assets/custom_bubble_100.png",
  "assets/custom_bubble_101.png",
  "assets/custom_bubble_102.png",
  "assets/custom_bubble_103.png",
  "assets/custom_bubble_104.png",
  "assets/custom_bubble_105.png",
  "assets/custom_bubble_106.png",
  "assets/custom_bubble_107.png",
  "assets/custom_bubble_108.png",
  "assets/custom_bubble_95.png",
  "assets/custom_bubble_96.png",
  "assets/custom_bubble_97.png",
  "assets/custom_bubble_98.png",
  "assets/custom_bubble_99.png",
  "assets/hall.png",
  "assets/item_58.png",
  "assets/item_59.png",
  "assets/item_60.png",
  "assets/item_61.png",
  "assets/item_62.png",
  "assets/item_63.png",
  "assets/item_64.png",
  "assets/item_65.png",
  "assets/item_66.png",
  "assets/item_67.png",
  "assets/item_68.png",
  "assets/item_69.png",
  "assets/item_70.png",
  "assets/item_71.png",
  "assets/item_72.png",
  "assets/item_73.png",
  "assets/item_74.png",
  "assets/item_75.png",
  "assets/item_76.png",
  "assets/item_77.png",
  "assets/item_78.png",
  "assets/item_79.png",
  "assets/loading.png",
  "assets/map_flopy_tile2.png",
  "assets/map_pirate_object1.png",
  "assets/map_pirate_object5.png",
  "assets/map_pirate_tile2.png",
  "assets/map_pirate_tile6.png",
  "assets/role_buzzi.png",
  "assets/role_cappi.png",
  "assets/role_dao.png",
  "assets/role_marid.png",
  "assets/role_selected.png",
  "assets/room_card_bg.png",
  "assets/room_card_default_img.png",
  "assets/room_card_status_in_game.png",
  "assets/room_card_status_waiting.png",
  "assets/room_player_card.png",
  "assets/room_player_card_none.png",
  "assets/unit_bombwater.png"
]

export enum COMMON_TEXTURE {
  'bazzi' = 'assets/bazzi.png',
'bg' = 'assets/bg.jpg',
'btn_blue' = 'assets/btn_blue.png',
'btn_create_room' = 'assets/btn_create_room.png',
'btn_next_page' = 'assets/btn_next_page.png',
'btn_pre_page' = 'assets/btn_pre_page.png',
'btn_room_start' = 'assets/btn_room_start.png',
'custom_bubble_100' = 'assets/custom_bubble_100.png',
'custom_bubble_101' = 'assets/custom_bubble_101.png',
'custom_bubble_102' = 'assets/custom_bubble_102.png',
'custom_bubble_103' = 'assets/custom_bubble_103.png',
'custom_bubble_104' = 'assets/custom_bubble_104.png',
'custom_bubble_105' = 'assets/custom_bubble_105.png',
'custom_bubble_106' = 'assets/custom_bubble_106.png',
'custom_bubble_107' = 'assets/custom_bubble_107.png',
'custom_bubble_108' = 'assets/custom_bubble_108.png',
'custom_bubble_95' = 'assets/custom_bubble_95.png',
'custom_bubble_96' = 'assets/custom_bubble_96.png',
'custom_bubble_97' = 'assets/custom_bubble_97.png',
'custom_bubble_98' = 'assets/custom_bubble_98.png',
'custom_bubble_99' = 'assets/custom_bubble_99.png',
'hall' = 'assets/hall.png',
'item_58' = 'assets/item_58.png',
'item_59' = 'assets/item_59.png',
'item_60' = 'assets/item_60.png',
'item_61' = 'assets/item_61.png',
'item_62' = 'assets/item_62.png',
'item_63' = 'assets/item_63.png',
'item_64' = 'assets/item_64.png',
'item_65' = 'assets/item_65.png',
'item_66' = 'assets/item_66.png',
'item_67' = 'assets/item_67.png',
'item_68' = 'assets/item_68.png',
'item_69' = 'assets/item_69.png',
'item_70' = 'assets/item_70.png',
'item_71' = 'assets/item_71.png',
'item_72' = 'assets/item_72.png',
'item_73' = 'assets/item_73.png',
'item_74' = 'assets/item_74.png',
'item_75' = 'assets/item_75.png',
'item_76' = 'assets/item_76.png',
'item_77' = 'assets/item_77.png',
'item_78' = 'assets/item_78.png',
'item_79' = 'assets/item_79.png',
'loading' = 'assets/loading.png',
'map_flopy_tile2' = 'assets/map_flopy_tile2.png',
'map_pirate_object1' = 'assets/map_pirate_object1.png',
'map_pirate_object5' = 'assets/map_pirate_object5.png',
'map_pirate_tile2' = 'assets/map_pirate_tile2.png',
'map_pirate_tile6' = 'assets/map_pirate_tile6.png',
'role_buzzi' = 'assets/role_buzzi.png',
'role_cappi' = 'assets/role_cappi.png',
'role_dao' = 'assets/role_dao.png',
'role_marid' = 'assets/role_marid.png',
'role_selected' = 'assets/role_selected.png',
'room_card_bg' = 'assets/room_card_bg.png',
'room_card_default_img' = 'assets/room_card_default_img.png',
'room_card_status_in_game' = 'assets/room_card_status_in_game.png',
'room_card_status_waiting' = 'assets/room_card_status_waiting.png',
'room_player_card' = 'assets/room_player_card.png',
'room_player_card_none' = 'assets/room_player_card_none.png',
'unit_bombwater' = 'assets/unit_bombwater.png'
}
    