export const GRID_WIDTH = 40
export const GRID_HEIGHT = 40
export const GRID_WIDTH_SIZE = 35
export const GRID_HEIGHT_SIZE = 20
export const STAGE_WIDTH = GRID_WIDTH * GRID_WIDTH_SIZE
export const STAGE_HEIGHT = GRID_HEIGHT * GRID_HEIGHT_SIZE
export const GRID_WIDTH_BOX2 = 26.5 * GRID_WIDTH
export const GRID_HEIGHT_BOX2 = 15.5 * GRID_HEIGHT
export const GRID_WIDTH_BOX3 = 26 * GRID_WIDTH
export const GRID_HEIGHT_BOX3 = 15 * GRID_HEIGHT